name: lint
on:
  push:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'

      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'latest'
          args: --timeout=5m

